//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinomix.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("kinomix.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///    Год выпуска: 1994
        ///    Страна: США
        ///    Слоган: «Страх - это кандалы. Надежда - это свобода.»
        ///    Жанр: Драма, Криминал
        ///    Качество: HDRip
        ///    Прод-сть: 142 мин.
        ///    Перевод: Профессиональный [Лицензия]
        ///    Премьера: (МИР) 10 Сентября (1994)
        ///    Режиссер: Фрэнк Дарабонт
        ///
        ///Актеры:
        ///Тим Роббинс,Морган Фриман,Боб Гантон,Уильям Сэдлер,Клэнси Браун,Джил Беллоуз,Марк Ролстон,Джеймс Уитмор,Ларри Бранденбург,Нил Джунтоли
        ///.
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///    Год выпуска: 2010
        ///    Страна: США
        ///    Слоган: «Some places never let you go.»
        ///    Жанр: Драма, Триллеры
        ///    Качество: BDRip
        ///    Прод-сть: 132 мин.
        ///    Перевод: Многоголосый
        ///    Премьера: (МИР) 13 Февраля (2010)
        ///    Режиссер: Мартин Скорсезе
        ///
        ///Актеры:
        ///Леонардо Ди Каприо, Марк Руффало, Бен Кингсли, Макс фон Сюдов, Мишель Уильямс, Эмили Мортимер, Патришия Кларксон, Джеки Эрл Хейли, Тед Ливайн, Джон Кэрролл Линч, Элиас Котеас, Робин Бартлетт, Кристофер Денэм, Нелли Скиутто, Джозеф Сикора
        ///.
        /// </summary>
        internal static string _10 {
            get {
                return ResourceManager.GetString("_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _101 {
            get {
                object obj = ResourceManager.GetObject("_101", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _11 {
            get {
                object obj = ResourceManager.GetObject("_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///    Год выпуска: 1999
        ///    Страна: США
        ///    Слоган: « - »
        ///    Жанр: Драма, Фэнтези
        ///    Качество: HDRip
        ///    Прод-сть: 189 мин.
        ///    Перевод: Дублированный
        ///    Премьера: 18 Апреля (2000)
        ///
        ///Актеры:
        ///Том Хэнкс,Майкл Кларк Дункан,Дэвид Морс,Бонни Хант,Джеймс Кромуэлл,Майкл Джитер,Грэм Грин,Даг Хатчисон,Сэм Рокуэлл,Барри Пеппер
        ///.
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _21 {
            get {
                object obj = ResourceManager.GetObject("_21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///    Год выпуска: 1994
        ///    Страна: США
        ///    Слоган: «Мир уже никогда не будет прежним, после того как вы увидите его глазами Форреста Гампа»
        ///    Жанр: Драма, Мелодрама
        ///    Качество: BDRip
        ///    Прод-сть: 142 мин.
        ///    Перевод: Дублированный [Лицензия]
        ///    Премьера: (МИР) 23 июня (1994)
        ///
        ///Актеры:
        ///Том Хэнкс,Робин Райт,Гэри Синиз,Майкелти Уильямсон,Салли Филд,Ребекка Уильямс,Майкл Коннер Хэмпфри,Харольд Дж. Хертэм,Джордж Келли,Боб Пенни
        ///.
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _31 {
            get {
                object obj = ResourceManager.GetObject("_31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///    Год выпуска: 1993
        ///    Страна: США
        ///    Слоган: «Этот список - жизнь.»
        ///    Жанр: Драма, Военные
        ///    Качество: HDRip
        ///    Прод-сть: 195 мин.
        ///    Перевод: Дублированный
        ///    Премьера: (МИР) 30 ноября (1993)
        ///
        ///Актеры:
        ///Лиам Нисон,Бен Кингсли,Рэйф Файнс,Кэролайн Гудолл,Джонатан Сагалл,Эмбет Дэвидц,Малгоша Гебель,Шмуэль Леви,Марк Иванир,Беатрис Макола
        ///.
        /// </summary>
        internal static string _4 {
            get {
                return ResourceManager.GetString("_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _41 {
            get {
                object obj = ResourceManager.GetObject("_41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///    Год выпуска: 1994
        ///    Страна: США
        ///    Слоган: «The Circle of Life»
        ///    Жанр: Мультфильмы
        ///    Качество: DVDRip
        ///    Прод-сть: 89 мин.
        ///    Перевод: Дублированный
        ///    Премьера: (МИР) 15 июня (1994)
        ///
        ///Актеры:
        ///Джереми Айронс,Мэттью Бродерик,Натан Лейн,Эрни Сабелла,Джеймс Эрл Джонс,Мойра Келли,Роуэн Эткинсон,Вупи Голдберг,Чич Марин,Джонатан Тейлор Томас
        ///.
        /// </summary>
        internal static string _5 {
            get {
                return ResourceManager.GetString("_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _51 {
            get {
                object obj = ResourceManager.GetObject("_51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///    Год выпуска: 2010
        ///    Страна: США, Великобритания
        ///    Слоган: «Твой разум - место преступления.»
        ///    Жанр: Боевики, Фантастика
        ///    Качество: HDRip
        ///    Прод-сть: 148 мин.
        ///    Перевод: Дублированный [Лицензия]
        ///    Премьера: (РФ) 22 Июля (2010)
        ///    Режиссер: Кен Ватанабе
        ///
        ///Актеры:
        ///Леонардо ДиКаприо,Кен Ватанабе,Джозеф Гордон-Левитт,Марион Котийяр,Эллен Пейдж,Том Харди,Киллиан Мёрфи,Том Беренджер,Майкл Кейн,Лукас Хаас
        ///.
        /// </summary>
        internal static string _6 {
            get {
                return ResourceManager.GetString("_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _61 {
            get {
                object obj = ResourceManager.GetObject("_61", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///    Год выпуска: 1999
        ///    Страна: США, Германия
        ///    Слоган: Интриги. Хаос. Мыло
        ///    Жанр: Драма, Триллеры, Криминал
        ///    Качество: BDRip
        ///    Прод-сть: 131 мин.
        ///    Перевод: Дублированный
        ///    Премьера: (МИР) 10 сентября (1999)
        ///    Режиссер: Дэвид Финчер
        ///
        ///Актеры:
        ///Эдвард Нортон,Брэд Питт,Хелена Бонем Картер,Мит Лоаф,Зэк Гренье,Ричмонд Аркетт,Дэвид Эндрюс,Джордж Магуайр,Эжени Бондюран,Кристина Кэбот
        ///.
        /// </summary>
        internal static string _7 {
            get {
                return ResourceManager.GetString("_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _71 {
            get {
                object obj = ResourceManager.GetObject("_71", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///    Год выпуска: 1997
        ///    Страна: Италия
        ///    Слоган: «An unforgettable fable that proves love, family and imagination conquer all.»
        ///    Жанр: Драма, Мелодрама
        ///    Качество: BDRip
        ///    Прод-сть: 118 мин.
        ///    Перевод: Дублированный [Лицензия]
        ///    Премьера: (МИР) 20 Декабря (1997)
        ///    Режиссер: Роберто Бениньи
        ///
        ///Актеры:
        ///Роберто Бениньи,Николетта Браски,Джорджио Кантарини,Джустино Дурано,Серджио Бини Бустрик,Мариса Паредес,Хорст Буххольц,Лидия Альфонси,Джулиана Лоджодиче,Америго Фонтани
        ///.
        /// </summary>
        internal static string _8 {
            get {
                return ResourceManager.GetString("_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _81 {
            get {
                object obj = ResourceManager.GetObject("_81", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///    Год выпуска: 1999
        ///    Страна: США, Австралия
        ///    Слоган: «The World&apos;s population thinks it&apos;s real. On March 31st, they will see the Real World.»
        ///    Жанр: Фантастика
        ///    Качество: BDRip
        ///    Прод-сть: 136 мин.
        ///    Перевод: Дублированный [Лицензия]
        ///    Премьера: (МИР) 14 Октября (1999)
        ///    Режиссер: Лилли Вачовски
        ///
        ///Актеры:
        ///Киану Ривз, Лоуренс Фишберн, Кэрри-Энн Мосс и др.
        ///.
        /// </summary>
        internal static string _9 {
            get {
                return ResourceManager.GetString("_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _91 {
            get {
                object obj = ResourceManager.GetObject("_91", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Burn After Reading
        /// 300 
        /// Alpha Dog
        /// Animatrix
        /// Armageddon
        /// Avatar
        /// Babylon A.D
        /// Batman Begins; The Dark Knight;
        /// Beowulf
        /// Cap America
        /// Charlie&apos;s Angels 
        /// Charlie&apos;s Angels 
        /// Clash of the Titans
        /// Constantine
        /// Cowboys &amp; Aliens
        /// Daredevil
        /// Equilibrium
        /// Evangelion 2.22
        /// Fantastic 4
        /// Fantastic 4 Rise of the Silver Surfer
        /// Final Fantasy VII
        /// G.I Joe The Rise Of Cobra
        /// Ghost Rider
        /// Green Lantern
        /// Harry Potter 4
        /// Harry Potter 5
        /// Harry Potter 6
        /// Harry Potter 7
        /// Harry Potter 8
        /// Hellboy 1 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string kinomix {
            get {
                return ResourceManager.GetString("kinomix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данная программа разработана сотрудниками  K&amp;K corp:
        ///Krivol Igor &amp; Strok Pavel
        ///____________________________________________________
        ///Название: KINOMIX
        ///Версия: 0.1 в бета тесте
        ///Функционал: в данной программе вы можете подобрать фильм рандомно, либо же перейти по ссылкам
        ///и посмотреть различные топы, а так же посетить проверенные сайты с фильмами и сериалами.
        ///_____________________________________________________
        ///В следующем обновлении будет увеличен рандом фильмов, переделан дизайн, расширен функционал. [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string О_программе {
            get {
                return ResourceManager.GetString("О_программе", resourceCulture);
            }
        }
    }
}
